# Generated by Django 4.2.10 on 2024-02-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movie_extract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='extract',
            field=models.CharField(max_length=1500),
        ),
    ]
