# Generated by Django 4.2.10 on 2024-02-18 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_movie_extract_alter_movie_href_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='window',
            old_name='time',
            new_name='hour',
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
