# Generated by Django 4.2.10 on 2024-02-20 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_usuario_correo_sala_formats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='time',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.time(15, 32, 4, 686261)),
        ),
    ]
