# Generated by Django 4.2.10 on 2024-02-26 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_reserva_fecha_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 17, 17, 56, 405567)),
        ),
    ]
