version: "3.7"
services:
    db:
        image: postgres:latest
        restart: always
        environment:
            # POSTGRES_DB: postgres
            # POSTGRES_USER: vgris
            POSTGRES_PASSWORD: contra123
            PGDATA: /var/lib/postgresql/data
        ports:
        - "5432:5432"
